module.exports = [
  { key: 'australia', name: 'GP Australia', circuit: 'Melbourne' },
  { key: 'cina', name: 'GP Cina', circuit: 'Shanghai' },
  { key: 'giappone', name: 'GP Giappone', circuit: 'Suzuka' },
  { key: 'arabia_saudita', name: 'GP Arabia Saudita', circuit: 'Gedda' },
  { key: 'miami', name: 'GP Miami', circuit: 'Miami International Autodrome' },
  { key: 'canada', name: 'GP Canada', circuit: 'Montréal' },
  { key: 'monaco', name: 'GP Monaco', circuit: 'Monte Carlo' },
  { key: 'spagna_barcellona', name: 'GP Spagna', circuit: 'Barcellona' },
  { key: 'austria', name: 'GP Austria', circuit: 'Red Bull Ring' },
  { key: 'gran_bretagna', name: 'GP Gran Bretagna', circuit: 'Silverstone' },
  { key: 'belgio', name: 'GP Belgio', circuit: 'Spa-Francorchamps' },
  { key: 'ungheria', name: 'GP Ungheria', circuit: 'Budapest' },
  { key: 'olanda', name: 'GP Olanda', circuit: 'Zandvoort' },
  { key: 'italia', name: 'GP Italia', circuit: 'Monza' },
  { key: 'spagna_madrid', name: 'GP Spagna (Madrid)', circuit: 'Madrid' },
  { key: 'azerbaigian', name: 'GP Azerbaigian', circuit: 'Baku' },
  { key: 'singapore', name: 'GP Singapore', circuit: 'Marina Bay' },
  { key: 'stati_uniti', name: 'GP Stati Uniti', circuit: 'Austin' },
  { key: 'messico', name: 'GP Città del Messico', circuit: 'Città del Messico' },
  { key: 'brasile', name: 'GP Brasile', circuit: 'San Paolo (Interlagos)' },
  { key: 'las_vegas', name: 'GP Las Vegas', circuit: 'Las Vegas' },
  { key: 'qatar', name: 'GP Qatar', circuit: 'Lusail' },
  { key: 'abu_dhabi', name: 'GP Abu Dhabi', circuit: 'Yas Marina' }
];
